security:
  encoders:
    TwinElements\AdminBundle\Entity\AdminUser: bcrypt
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_EDIT:    ROLE_OBSERVER
    ROLE_SLIDER_EDIT: ROLE_SLIDER_VIEW
    ROLE_CARD_EDIT: ROLE_CARD_VIEW
    ROLE_ADMIN: [ROLE_EDIT, ROLE_SLIDER_EDIT, ROLE_CARD_EDIT, ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    admin:
      entity: { class: TwinElements\AdminBundle\Entity\AdminUser, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    admin:
      anonymous: true
      provider: admin
      pattern: ^/admin/
      guard:
        authenticators:
          - TwinElements\AdminBundle\Security\LoginFormAuthenticator
      form_login:
        login_path: security_login
        check_path: security_login
        csrf_token_generator: security.csrf.token_manager
        default_target_path: admin_dashboard
      logout:
        path: security_logout
        target: /admin/
      security: true
      switch_user: true

  access_control:
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/.*, roles: ROLE_USER }
